# Generated by Django 4.0.3 on 2022-03-31 13:29

import adminfile.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(storage=adminfile.models.OverwriteStorage, upload_to='result/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])]),
        ),
    ]
